package runtime

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// Use a subprocess speaking the JSON-RPC contract generated by the installed
// Codex app-server. It requires a single initialize/initialized handshake and
// enforces the read-only settings; no provider credentials or model are used.
func TestCodexProtocolHelper(t *testing.T) {
	if os.Getenv("RCG_CODEX_PROTOCOL_HELPER") != "1" {
		return
	}
	sc := bufio.NewScanner(os.Stdin)
	enc := json.NewEncoder(os.Stdout)
	initialized, notified, threads := false, false, 0
	for sc.Scan() {
		var req struct {
			ID     any             `json:"id"`
			Method string          `json:"method"`
			Params json.RawMessage `json:"params"`
		}
		if json.Unmarshal(sc.Bytes(), &req) != nil {
			os.Exit(10)
		}
		reply := func(result any) {
			if enc.Encode(map[string]any{"id": req.ID, "result": result}) != nil {
				os.Exit(11)
			}
		}
		emit := func(method string, params any) {
			if enc.Encode(map[string]any{"method": method, "params": params}) != nil {
				os.Exit(12)
			}
		}
		if req.Method == "initialize" {
			if initialized {
				enc.Encode(map[string]any{"id": req.ID, "error": map[string]any{"code": -1, "message": "already initialized"}})
				continue
			}
			initialized = true
			reply(map[string]any{})
			continue
		}
		if req.Method == "initialized" {
			notified = true
			continue
		}
		if !initialized || !notified {
			os.Exit(13)
		}
		switch req.Method {
		case "thread/start", "thread/resume":
			var p struct {
				Sandbox  string `json:"sandbox"`
				Approval string `json:"approvalPolicy"`
				ThreadID string `json:"threadId"`
			}
			if json.Unmarshal(req.Params, &p) != nil || p.Sandbox != "read-only" || p.Approval != "never" {
				os.Exit(14)
			}
			if p.ThreadID == "" {
				threads++
				p.ThreadID = fmt.Sprintf("thread-%d", threads)
			}
			reply(map[string]any{"thread": map[string]any{"id": p.ThreadID}})
		case "turn/start":
			if target := os.Getenv("RCG_TEST_TURN_PARAMS"); target != "" {
				if e := os.WriteFile(target, req.Params, 0600); e != nil {
					os.Exit(19)
				}
			}
			var p struct {
				ThreadID string `json:"threadId"`
				Sandbox  struct {
					Type string `json:"type"`
				} `json:"sandboxPolicy"`
				Input []struct {
					Text string `json:"text"`
				} `json:"input"`
			}
			if json.Unmarshal(req.Params, &p) != nil || p.Sandbox.Type != "readOnly" || len(p.Input) != 1 {
				os.Exit(15)
			}
			prompt := p.Input[0].Text
			if prompt == "block-start" {
				time.Sleep(30 * time.Second)
				continue
			}
			turnID := fmt.Sprintf("turn-%v", req.ID)
			reply(map[string]any{"turn": map[string]any{"id": turnID, "status": "inProgress"}})
			if prompt == "block-turn" {
				time.Sleep(30 * time.Second)
				continue
			}
			emit("item/agentMessage/delta", map[string]string{"threadId": p.ThreadID, "delta": "first "})
			// An unrelated idle notification is not proof of turn completion.
			emit("thread/status/changed", map[string]any{"threadId": "another-thread", "status": map[string]string{"type": "idle"}})
			emit("item/agentMessage/delta", map[string]string{"threadId": p.ThreadID, "delta": "second"})
			status := "completed"
			if prompt == "fail" {
				status = "failed"
			}
			emit("turn/completed", map[string]any{"threadId": p.ThreadID, "turn": map[string]string{"id": turnID, "status": status}})
		}
	}
	os.Exit(0)
}

func codexFixture(t *testing.T) string {
	t.Helper()
	exe, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	t.Setenv("RCG_CODEX_TEST_EXECUTABLE", exe)
	t.Setenv("RCG_CODEX_PROTOCOL_HELPER", "1")
	script := filepath.Join(t.TempDir(), "codex-fixture")
	if err = os.WriteFile(script, []byte("#!/bin/sh\nexec \"$RCG_CODEX_TEST_EXECUTABLE\" -test.run=^TestCodexProtocolHelper$ -- \"$@\"\n"), 0700); err != nil {
		t.Fatal(err)
	}
	return script
}

func TestCodexReadonlyResumeAndCompletion(t *testing.T) {
	command := codexFixture(t)
	rt := NewCodex(command)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	s, err := rt.Start(ctx, t.TempDir(), "", "readonly", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = rt.Stop() }()
	other, err := rt.Start(ctx, s.CWD, "", "readonly", nil)
	if err != nil || other.ID == s.ID {
		t.Fatalf("second start=%+v error=%v", other, err)
	}
	if result, err := rt.Turn(ctx, s, "success", nil); err != nil || result != "first second" {
		t.Fatalf("result=%q error=%v", result, err)
	}
	if err = rt.Stop(); err != nil {
		t.Fatal(err)
	}
	rt = NewCodex(command)
	resumed, err := rt.Resume(ctx, s, nil)
	if err != nil || resumed.ID != s.ID {
		t.Fatalf("resume=%+v error=%v", resumed, err)
	}
	if result, err := rt.Turn(ctx, resumed, "success", nil); err != nil || result != "first second" {
		t.Fatalf("resumed result=%q error=%v", result, err)
	}
	if _, err = rt.Turn(ctx, resumed, "fail", nil); err == nil {
		t.Fatal("failed completion acknowledged as success")
	}
}

func TestCodexCancellationAndEventFailureReapProcess(t *testing.T) {
	command := codexFixture(t)
	for _, prompt := range []string{"block-start", "block-turn", "handler-failure"} {
		t.Run(prompt, func(t *testing.T) {
			rt := NewCodex(command).(*Codex)
			defer rt.Stop()
			s, err := rt.Start(context.Background(), t.TempDir(), "", "readonly", nil)
			if err != nil {
				t.Fatal(err)
			}
			rt.mu.Lock()
			child := rt.proc
			rt.mu.Unlock()
			ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
			defer cancel()
			var handler Handler
			want := error(context.DeadlineExceeded)
			if prompt == "handler-failure" {
				want = errors.New("event persistence unavailable")
				handler = func(Event) error { return want }
			}
			_, err = rt.Turn(ctx, s, prompt, handler)
			if !errors.Is(err, want) {
				t.Fatalf("error=%v want=%v", err, want)
			}
			if child.ProcessState == nil {
				t.Fatal("process was not reaped before returning")
			}
			if _, err = rt.Resume(context.Background(), s, nil); err != nil {
				t.Fatal(err)
			}
			if _, err = rt.Turn(context.Background(), s, "success", nil); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestCodexModelAndEffortReachResumedTurn(t *testing.T) {
	command := codexFixture(t)
	capture := filepath.Join(t.TempDir(), "params.json")
	t.Setenv("RCG_TEST_TURN_PARAMS", capture)
	rt := NewCodex(command)
	defer rt.Stop()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	s, err := rt.Start(ctx, t.TempDir(), "", "readonly", nil)
	if err != nil {
		t.Fatal(err)
	}
	s.Model = "selected-model"
	s.Effort = "ultra"
	s, err = rt.Resume(ctx, s, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = rt.Turn(ctx, s, "success", nil); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(capture)
	if err != nil {
		t.Fatal(err)
	}
	var params map[string]any
	if err = json.Unmarshal(b, &params); err != nil {
		t.Fatal(err)
	}
	if params["model"] != "selected-model" || params["effort"] != "ultra" {
		t.Fatalf("turn settings: %s", b)
	}
}
