import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { parseEnvFile } from "./config.mjs";

function quoteEnv(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

function parseTomlString(value) {
  const match = String(value).trim().match(/^["'](.*)["']$/);
  return match ? match[1] : String(value).trim();
}

export function discoverCodexProviders({ codexHome = path.join(os.homedir(), ".codex") } = {}) {
  const configPath = path.join(codexHome, "config.toml");
  let text = "";
  try { text = fs.readFileSync(configPath, "utf8"); } catch { return { configPath, defaultProvider: "custom", providers: [] }; }
  const root = {};
  for (const line of text.split(/\r?\n/)) {
    const match = line.match(/^\s*(model_provider|model|model_catalog_json)\s*=\s*(.+?)\s*(?:#.*)?$/);
    if (match) root[match[1]] = parseTomlString(match[2]);
  }
  const providers = [];
  const sectionPattern = /^\s*\[model_providers\.([A-Za-z0-9_-]+)\]\s*$/gm;
  let match;
  while ((match = sectionPattern.exec(text))) {
    const provider = match[1];
    const start = match.index + match[0].length;
    const nextSection = text.slice(start).search(/^\s*\[/m);
    const section = text.slice(start, nextSection < 0 ? text.length : start + nextSection);
    const values = {};
    for (const line of section.split(/\r?\n/)) {
      const valueMatch = line.match(/^\s*(name|env_key|base_url|wire_api)\s*=\s*(.+?)\s*(?:#.*)?$/);
      if (valueMatch) values[valueMatch[1]] = parseTomlString(valueMatch[2]);
    }
    providers.push({ provider, name: values.name || provider, envKey: values.env_key, baseUrl: values.base_url, wireApi: values.wire_api });
  }
  return { configPath, defaultProvider: root.model_provider || providers[0]?.provider || "custom", model: root.model, modelCatalogJson: root.model_catalog_json, providers };
}

async function fetchProviderModels(provider) {
  if (!provider.baseUrl || !provider.envKey || !process.env[provider.envKey]) return [];
  try {
    const base = provider.baseUrl.replace(/\/+$/, "");
    const response = await fetch(`${base}/models`, {
      headers: { Authorization: `Bearer ${process.env[provider.envKey]}`, Accept: "application/json" },
      signal: AbortSignal.timeout(5000),
    });
    if (!response.ok) return [];
    const payload = await response.json();
    return (Array.isArray(payload) ? payload : payload?.data ?? [])
      .map((item) => String(item?.id ?? item?.slug ?? "").trim()).filter(Boolean).slice(0, 200);
  } catch { return []; }
}

export async function discoverModelCatalog({ codexHome = path.join(os.homedir(), ".codex"), includeNetwork = true } = {}) {
  const discovered = discoverCodexProviders({ codexHome });
  const result = [];
  for (const provider of discovered.providers) {
    const models = includeNetwork ? await fetchProviderModels(provider) : [];
    result.push({ provider: provider.provider, models });
  }
  if (result.length === 0) result.push({ provider: discovered.defaultProvider, models: discovered.model ? [discovered.model] : [] });
  if (result.every((entry) => entry.models.length === 0) && discovered.model) {
    const fallback = result.find((entry) => entry.provider === discovered.defaultProvider) || result[0];
    fallback.models = [discovered.model];
  }
  return { ...discovered, providers: result };
}

function writeEnvFile(filePath, values) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const lines = [
    "# Generated by rcodex-gateway setup. Edit provider names/models if needed.",
    ...Object.entries(values).map(([key, value]) => `${key}=${quoteEnv(value)}`),
    "",
  ];
  const temporary = `${filePath}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, lines.join("\n"), { mode: 0o600 });
  fs.renameSync(temporary, filePath);
  fs.chmodSync(filePath, 0o600);
}

export function generateGatewayEnv({ envFile, discovery, workspacePath, port = 8787, password, token, name = "rcodex-gateway" }) {
  const providers = Object.fromEntries(discovery.providers.map((entry) => [entry.provider, entry.models]));
  const fallbackModels = discovery.providers.flatMap((entry) => entry.models);
  const command = process.env.CODEX_COMMAND || "codex";
  const values = {
    GATEWAY_NAME: name,
    GATEWAY_HOST: "127.0.0.1",
    GATEWAY_PORT: String(port),
    GATEWAY_DATA_DIR: path.join(path.dirname(envFile), "data"),
    GATEWAY_ALLOWED_PATHS: workspacePath || os.homedir(),
    GATEWAY_AUTH_USERNAME: "admin",
    GATEWAY_AUTH_PASSWORD: password || crypto.randomBytes(18).toString("base64url"),
    GATEWAY_AUTH_TOKEN: token || crypto.randomBytes(24).toString("hex"),
    CODEX_COMMAND: command,
    CODEX_DEFAULT_MODEL_PROVIDER: discovery.defaultProvider,
    CODEX_AVAILABLE_MODELS: fallbackModels.join(" "),
    CODEX_MODEL_PROVIDERS: JSON.stringify(providers),
    GATEWAY_PERMISSION_MODE: "full",
  };
  writeEnvFile(envFile, values);
  return { envFile, values, discovery };
}

export function serviceUnitPath({ home = os.homedir() } = {}) {
  return path.join(home, ".config", "systemd", "user", "rcodex-gateway.service");
}

export function generateServiceUnit({ envFile, gatewayRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), nodeCommand = process.execPath, home = os.homedir() }) {
  const unitPath = serviceUnitPath({ home });
  const unit = `[Unit]\nDescription=rCodex Gateway (open-source)\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nWorkingDirectory=${gatewayRoot}\nEnvironment=RCODEX_GATEWAY_ENV=${envFile}\nExecStart=${nodeCommand} ${path.join(gatewayRoot, "src", "cli.mjs")} service run\nRestart=on-failure\nRestartSec=3\n\n[Install]\nWantedBy=default.target\n`;
  fs.mkdirSync(path.dirname(unitPath), { recursive: true });
  fs.writeFileSync(unitPath, unit, { mode: 0o600 });
  return unitPath;
}

export async function runSetup(options = {}) {
  const home = os.homedir();
  const envFile = path.resolve(options.envFile || path.join(home, ".rcodex", "gateway", "gateway.env"));
  const existing = fs.existsSync(envFile) ? parseEnvFile(fs.readFileSync(envFile, "utf8")) : {};
  let workspacePath = options.workspacePath ? path.resolve(options.workspacePath) : path.resolve(existing.GATEWAY_ALLOWED_PATHS || home);
  let port = Number(options.port || existing.GATEWAY_PORT || 8787);
  let password = options.password;
  const token = options.token || existing.GATEWAY_AUTH_TOKEN;
  password ||= existing.GATEWAY_AUTH_PASSWORD;
  const discovery = await discoverModelCatalog({ codexHome: options.codexHome || path.join(home, ".codex"), includeNetwork: options.network !== false });
  if (!options.nonInteractive) {
    const rl = readline.createInterface({ input, output });
    workspacePath = path.resolve((await rl.question(`工作区 [${workspacePath}]: `)).trim() || workspacePath);
    const portText = (await rl.question(`端口 [${port}]: `)).trim();
    if (portText) port = Number(portText);
    password = (await rl.question("登录密码（留空自动生成）: ")).trim() || password;
    rl.close();
  }
  if (!Number.isInteger(port) || port <= 0 || port > 65535) throw new Error("invalid gateway port");
  const generated = generateGatewayEnv({ envFile, discovery, workspacePath, port, password, token, name: options.name || existing.GATEWAY_NAME || "rcodex-gateway" });
  let unitPath;
  if (options.installService) unitPath = generateServiceUnit({ envFile });
  return { ...generated, unitPath };
}
